### ISSUE TITLE
Some encounter-data appears to be missing.

### ISSUE THREAD

**Issue by yatsuna827** [LegoFigure11/swsh-overworld-rng-gui#20]
3番道路に出現するアオガラスと、ルミナスメイズの森に出現するベロバー、ギモーの固定シンボルのデータが無いようです。
これらのポケモンはOverworld RNGの対象ですか？

There seems to be no data of `EncouterType: Static` for Corvisquire that appears on Road 3 and Impidimp and Morgrem that appear in Glimwood Tangle.
Are these Pokémon eligible for Overworld RNG?

**Comment by LegoFigure11** [comment]
I'm unsure about the Corvisquire, but as per https://gist.github.com/Lusamine/e17168d92019672c1f9dcc1a246d9818#these-encounters-do-not-use-overworld-rng the Impidimp and Morgrem are scripted encounters do not use the Overworld RNG. I will be able to check the Corvisquire later today and I will get back to you regarding that one!

**Comment by LegoFigure11** [comment]
The Route 3 Corvisquire does use Overworld RNG!
![image](https://user-images.githubusercontent.com/24732684/174482157-cf3baca4-2200-432e-b5b3-9089e0aa6faa.png)
It is a static encounter with Shiny Lock. I will add it to the JSON later and close this issue when I do. Thank you for pointing this out!

**Comment by LegoFigure11** [comment]
Please note I added a new `boolean | null` field "`ShinyLocked`" to the JSON and you may need to update your TypeScript to account for this ^^"
