### ISSUE TITLE
IV Spread Shortcuts

### ISSUE THREAD

**Issue by butterholes** [LegoFigure11/swsh-overworld-rng-gui#23]
A QoL update to the IV search parameters would be lovely! A drop down for certain IVs already exists, (No Good, Best, etc.) so the spreads could be added to the drop down, or a click shortcut could be added to each stat value. Some IV shortcuts could include 0-31, 30-31, 31-31, 0-0, 0-1. I don't see importance in any other IV ranges.

I understand that functionality is 3,000% more important than QoL, I just had the thought and wanted to share!

**Comment by LegoFigure11** [comment]
0-0 can by done by clicking the "0" button on the relevant stat
0-1 can be done by clicking in "0" button while holding "Shift"
31-31 can be done by clicking the "31" button on the relevant stat
30-31 can be done by clicking in "31" button while holding "Shift"
0-31 (aka reset) can be done by clicking on the relevant stat label/stat name

![](https://i.imgur.com/dzr15dq.gif)
