### ISSUE TITLE
Net framework

### ISSUE THREAD

**Issue by Encefaloraptor** [LegoFigure11/swsh-overworld-rng-gui#26]
Cant open the app at all, gives an issue of missing frameworks but after going back and forth installing and reinstalling it just wont work.

**Comment by ABKTiltControls** [comment]
Did you figure out how to fix this issue? I am running into something very similar, except I get nothing at all when running the exe

**Comment by LegoFigure11** [comment]
@ABKTiltControls I'd suggest installing the [.NET 6.0 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime), restarting your computer, and trying again as that will probably solve your issue. You most likely want "Run desktop apps" > "x64".

**Comment by Encefaloraptor** [comment]
> 

Yes, just download everything from the net 6.0 runtime that works with your PC ,x64 in my case. Ended up working finally.

**Comment by Encefaloraptor** [comment]
> @ABKTiltControls I'd suggest installing the [.NET 6.0 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime), restarting your computer, and trying again as that will probably solve your issue. You most likely want "Run desktop apps" > "x64".

It seemed that it wanted something else cause I kept doing this exact thing over and over without any sucess since it seemed the most logical thing, until I downloaded everything from the page and worked.
