### ISSUE TITLE
i have a 6 digit sid

### ISSUE THREAD

**Issue by jhepp721** [LegoFigure11/swsh-overworld-rng-gui#28]
the program cuts me off at 5 digits

**Comment by LegoFigure11** [comment]
This program requires the 5-digit TID/SID pair, not the 6-digit Display ID used by the games.

To get your 5-digit values, open a Pokemon file in PKHeX and hover your mouse over the IDs.
![image](https://user-images.githubusercontent.com/24732684/197991647-8dd6112c-e620-4e0d-ba7b-6965c878dc2e.png)
In this example, the TID would be 09529 and the SID would be 33906

If you don't have access to a sysbot to dump a pokemon file (there are hundreds, just google) or cfw to extract one directly, you can also manually calculate your IDs using thet "Search for TID/SID" mode in the program. But it's considerably easier to just use PKHeX to read it from a file.
