### ISSUE TITLE
Reverse TID/SID search broken

### ISSUE THREAD

**Issue by notblisy** [LegoFigure11/swsh-overworld-rng-gui#9]
When doing a reverse search for a TID/SID after finding an overworld shiny by checking the TID/SID box, it is taking into account the TID/SID in the TID/SID box.  

![knownTIDSID](https://user-images.githubusercontent.com/50887637/155750290-6b351d96-61da-47e2-99e0-c08dc90337fa.png)
Here, before checking the box, I input my TID/SID found via hacking. It produces a result, and seemingly finds the Chewtle I hunted for. I'm not even positive this is the actual Chewtle, since its level is incorrect anyway. 
Note, the Chewtle was a brilliant overworld shiny on route 2, but changing the level / encounter slots dont effect the results in any way here.

![randomtidsid](https://user-images.githubusercontent.com/50887637/155750305-a3eb9dc6-1e10-4747-ad5a-8c98fabacdbb.png)
Here, there is a random TID/SID in the box, and it produces no results.

**Comment by Lincoln-LM** [comment]
https://github.com/LegoFigure11/swsh-overworld-rng-gui/blob/f44c0989c8ed63e66a8962f346bc868b4b80f4b3/SWSH_OWRNG_Generator_GUI/Generator.cs#L108

relevant line, tid/sid search does not properly account for extra rerolls and spreads that are only possible when the fake pid generation stops at the correct point will not be displayed. a solution may be checking each reroll and assuming they're shiny, or have the tid/sid search check every fixed seed at every advance by skipping the slot/level/fakePID generation.

**Comment by LegoFigure11** [comment]
b498f77 fixes the incorrect Chewtle generating. 
@Lincoln-LM I'm not super sure I understand your explanation, but seeing as you write this feature and seem to know what's going on, would you mind fixing it?

**Comment by LegoFigure11** [comment]
I have disabled this feature in d11b450 until its fixed. @Lincoln-LM bump
